//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestJediService.ServiceJediReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceJediReference.IServiceJedi")]
    public interface IServiceJedi {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceJedi/getAllJedi", ReplyAction="http://tempuri.org/IServiceJedi/getAllJediResponse")]
        System.Collections.Generic.List<JediService.BusinessWCF.JediWCF> getAllJedi();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceJedi/getAllJedi", ReplyAction="http://tempuri.org/IServiceJedi/getAllJediResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<JediService.BusinessWCF.JediWCF>> getAllJediAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceJedi/getAllMatch", ReplyAction="http://tempuri.org/IServiceJedi/getAllMatchResponse")]
        System.Collections.Generic.List<JediService.BusinessWCF.MatchWCF> getAllMatch();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceJedi/getAllMatch", ReplyAction="http://tempuri.org/IServiceJedi/getAllMatchResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<JediService.BusinessWCF.MatchWCF>> getAllMatchAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceJedi/getAllStade", ReplyAction="http://tempuri.org/IServiceJedi/getAllStadeResponse")]
        System.Collections.Generic.List<JediService.BusinessWCF.StadeWCF> getAllStade();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceJedi/getAllStade", ReplyAction="http://tempuri.org/IServiceJedi/getAllStadeResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<JediService.BusinessWCF.StadeWCF>> getAllStadeAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceJedi/getAllTournoi", ReplyAction="http://tempuri.org/IServiceJedi/getAllTournoiResponse")]
        System.Collections.Generic.List<JediService.BusinessWCF.TournoiWCF> getAllTournoi();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceJedi/getAllTournoi", ReplyAction="http://tempuri.org/IServiceJedi/getAllTournoiResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<JediService.BusinessWCF.TournoiWCF>> getAllTournoiAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceJedi/getAllCaracteristique", ReplyAction="http://tempuri.org/IServiceJedi/getAllCaracteristiqueResponse")]
        System.Collections.Generic.List<JediService.BusinessWCF.CaracteristiqueWCF> getAllCaracteristique();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceJedi/getAllCaracteristique", ReplyAction="http://tempuri.org/IServiceJedi/getAllCaracteristiqueResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<JediService.BusinessWCF.CaracteristiqueWCF>> getAllCaracteristiqueAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceJedi/addJedi", ReplyAction="http://tempuri.org/IServiceJedi/addJediResponse")]
        void addJedi(JediService.BusinessWCF.JediWCF jedi);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceJedi/addJedi", ReplyAction="http://tempuri.org/IServiceJedi/addJediResponse")]
        System.Threading.Tasks.Task addJediAsync(JediService.BusinessWCF.JediWCF jedi);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceJedi/addMatch", ReplyAction="http://tempuri.org/IServiceJedi/addMatchResponse")]
        void addMatch(JediService.BusinessWCF.MatchWCF match);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceJedi/addMatch", ReplyAction="http://tempuri.org/IServiceJedi/addMatchResponse")]
        System.Threading.Tasks.Task addMatchAsync(JediService.BusinessWCF.MatchWCF match);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceJedi/addStade", ReplyAction="http://tempuri.org/IServiceJedi/addStadeResponse")]
        void addStade(JediService.BusinessWCF.StadeWCF stade);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceJedi/addStade", ReplyAction="http://tempuri.org/IServiceJedi/addStadeResponse")]
        System.Threading.Tasks.Task addStadeAsync(JediService.BusinessWCF.StadeWCF stade);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceJedi/addTournoi", ReplyAction="http://tempuri.org/IServiceJedi/addTournoiResponse")]
        void addTournoi(JediService.BusinessWCF.TournoiWCF tournoi);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceJedi/addTournoi", ReplyAction="http://tempuri.org/IServiceJedi/addTournoiResponse")]
        System.Threading.Tasks.Task addTournoiAsync(JediService.BusinessWCF.TournoiWCF tournoi);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceJedi/addCracteristique", ReplyAction="http://tempuri.org/IServiceJedi/addCracteristiqueResponse")]
        void addCracteristique(JediService.BusinessWCF.CaracteristiqueWCF caract);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceJedi/addCracteristique", ReplyAction="http://tempuri.org/IServiceJedi/addCracteristiqueResponse")]
        System.Threading.Tasks.Task addCracteristiqueAsync(JediService.BusinessWCF.CaracteristiqueWCF caract);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceJedi/deleteJedi", ReplyAction="http://tempuri.org/IServiceJedi/deleteJediResponse")]
        void deleteJedi(JediService.BusinessWCF.JediWCF jedi);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceJedi/deleteJedi", ReplyAction="http://tempuri.org/IServiceJedi/deleteJediResponse")]
        System.Threading.Tasks.Task deleteJediAsync(JediService.BusinessWCF.JediWCF jedi);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceJedi/deleteMatch", ReplyAction="http://tempuri.org/IServiceJedi/deleteMatchResponse")]
        void deleteMatch(JediService.BusinessWCF.MatchWCF match);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceJedi/deleteMatch", ReplyAction="http://tempuri.org/IServiceJedi/deleteMatchResponse")]
        System.Threading.Tasks.Task deleteMatchAsync(JediService.BusinessWCF.MatchWCF match);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceJedi/deleteStade", ReplyAction="http://tempuri.org/IServiceJedi/deleteStadeResponse")]
        void deleteStade(JediService.BusinessWCF.StadeWCF stade);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceJedi/deleteStade", ReplyAction="http://tempuri.org/IServiceJedi/deleteStadeResponse")]
        System.Threading.Tasks.Task deleteStadeAsync(JediService.BusinessWCF.StadeWCF stade);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceJedi/deleteTournois", ReplyAction="http://tempuri.org/IServiceJedi/deleteTournoisResponse")]
        void deleteTournois(JediService.BusinessWCF.TournoiWCF tournoi);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceJedi/deleteTournois", ReplyAction="http://tempuri.org/IServiceJedi/deleteTournoisResponse")]
        System.Threading.Tasks.Task deleteTournoisAsync(JediService.BusinessWCF.TournoiWCF tournoi);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceJedi/deleteCaracteristique", ReplyAction="http://tempuri.org/IServiceJedi/deleteCaracteristiqueResponse")]
        void deleteCaracteristique(JediService.BusinessWCF.CaracteristiqueWCF caract);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceJedi/deleteCaracteristique", ReplyAction="http://tempuri.org/IServiceJedi/deleteCaracteristiqueResponse")]
        System.Threading.Tasks.Task deleteCaracteristiqueAsync(JediService.BusinessWCF.CaracteristiqueWCF caract);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceJedi/updateJedi", ReplyAction="http://tempuri.org/IServiceJedi/updateJediResponse")]
        void updateJedi(JediService.BusinessWCF.JediWCF jedi);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceJedi/updateJedi", ReplyAction="http://tempuri.org/IServiceJedi/updateJediResponse")]
        System.Threading.Tasks.Task updateJediAsync(JediService.BusinessWCF.JediWCF jedi);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceJedi/updateMatch", ReplyAction="http://tempuri.org/IServiceJedi/updateMatchResponse")]
        void updateMatch(JediService.BusinessWCF.MatchWCF match);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceJedi/updateMatch", ReplyAction="http://tempuri.org/IServiceJedi/updateMatchResponse")]
        System.Threading.Tasks.Task updateMatchAsync(JediService.BusinessWCF.MatchWCF match);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceJedi/updateStade", ReplyAction="http://tempuri.org/IServiceJedi/updateStadeResponse")]
        void updateStade(JediService.BusinessWCF.StadeWCF stade);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceJedi/updateStade", ReplyAction="http://tempuri.org/IServiceJedi/updateStadeResponse")]
        System.Threading.Tasks.Task updateStadeAsync(JediService.BusinessWCF.StadeWCF stade);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceJedi/updateTournois", ReplyAction="http://tempuri.org/IServiceJedi/updateTournoisResponse")]
        void updateTournois(JediService.BusinessWCF.TournoiWCF tournoi);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceJedi/updateTournois", ReplyAction="http://tempuri.org/IServiceJedi/updateTournoisResponse")]
        System.Threading.Tasks.Task updateTournoisAsync(JediService.BusinessWCF.TournoiWCF tournoi);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceJedi/updateCaracteristique", ReplyAction="http://tempuri.org/IServiceJedi/updateCaracteristiqueResponse")]
        void updateCaracteristique(JediService.BusinessWCF.CaracteristiqueWCF caract);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceJedi/updateCaracteristique", ReplyAction="http://tempuri.org/IServiceJedi/updateCaracteristiqueResponse")]
        System.Threading.Tasks.Task updateCaracteristiqueAsync(JediService.BusinessWCF.CaracteristiqueWCF caract);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceJedi/playTournoi", ReplyAction="http://tempuri.org/IServiceJedi/playTournoiResponse")]
        JediService.BusinessWCF.TournoiWCF playTournoi(JediService.BusinessWCF.TournoiWCF tournoi);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceJedi/playTournoi", ReplyAction="http://tempuri.org/IServiceJedi/playTournoiResponse")]
        System.Threading.Tasks.Task<JediService.BusinessWCF.TournoiWCF> playTournoiAsync(JediService.BusinessWCF.TournoiWCF tournoi);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceJediChannel : TestJediService.ServiceJediReference.IServiceJedi, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceJediClient : System.ServiceModel.ClientBase<TestJediService.ServiceJediReference.IServiceJedi>, TestJediService.ServiceJediReference.IServiceJedi {
        
        public ServiceJediClient() {
        }
        
        public ServiceJediClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceJediClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceJediClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceJediClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<JediService.BusinessWCF.JediWCF> getAllJedi() {
            return base.Channel.getAllJedi();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<JediService.BusinessWCF.JediWCF>> getAllJediAsync() {
            return base.Channel.getAllJediAsync();
        }
        
        public System.Collections.Generic.List<JediService.BusinessWCF.MatchWCF> getAllMatch() {
            return base.Channel.getAllMatch();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<JediService.BusinessWCF.MatchWCF>> getAllMatchAsync() {
            return base.Channel.getAllMatchAsync();
        }
        
        public System.Collections.Generic.List<JediService.BusinessWCF.StadeWCF> getAllStade() {
            return base.Channel.getAllStade();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<JediService.BusinessWCF.StadeWCF>> getAllStadeAsync() {
            return base.Channel.getAllStadeAsync();
        }
        
        public System.Collections.Generic.List<JediService.BusinessWCF.TournoiWCF> getAllTournoi() {
            return base.Channel.getAllTournoi();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<JediService.BusinessWCF.TournoiWCF>> getAllTournoiAsync() {
            return base.Channel.getAllTournoiAsync();
        }
        
        public System.Collections.Generic.List<JediService.BusinessWCF.CaracteristiqueWCF> getAllCaracteristique() {
            return base.Channel.getAllCaracteristique();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<JediService.BusinessWCF.CaracteristiqueWCF>> getAllCaracteristiqueAsync() {
            return base.Channel.getAllCaracteristiqueAsync();
        }
        
        public void addJedi(JediService.BusinessWCF.JediWCF jedi) {
            base.Channel.addJedi(jedi);
        }
        
        public System.Threading.Tasks.Task addJediAsync(JediService.BusinessWCF.JediWCF jedi) {
            return base.Channel.addJediAsync(jedi);
        }
        
        public void addMatch(JediService.BusinessWCF.MatchWCF match) {
            base.Channel.addMatch(match);
        }
        
        public System.Threading.Tasks.Task addMatchAsync(JediService.BusinessWCF.MatchWCF match) {
            return base.Channel.addMatchAsync(match);
        }
        
        public void addStade(JediService.BusinessWCF.StadeWCF stade) {
            base.Channel.addStade(stade);
        }
        
        public System.Threading.Tasks.Task addStadeAsync(JediService.BusinessWCF.StadeWCF stade) {
            return base.Channel.addStadeAsync(stade);
        }
        
        public void addTournoi(JediService.BusinessWCF.TournoiWCF tournoi) {
            base.Channel.addTournoi(tournoi);
        }
        
        public System.Threading.Tasks.Task addTournoiAsync(JediService.BusinessWCF.TournoiWCF tournoi) {
            return base.Channel.addTournoiAsync(tournoi);
        }
        
        public void addCracteristique(JediService.BusinessWCF.CaracteristiqueWCF caract) {
            base.Channel.addCracteristique(caract);
        }
        
        public System.Threading.Tasks.Task addCracteristiqueAsync(JediService.BusinessWCF.CaracteristiqueWCF caract) {
            return base.Channel.addCracteristiqueAsync(caract);
        }
        
        public void deleteJedi(JediService.BusinessWCF.JediWCF jedi) {
            base.Channel.deleteJedi(jedi);
        }
        
        public System.Threading.Tasks.Task deleteJediAsync(JediService.BusinessWCF.JediWCF jedi) {
            return base.Channel.deleteJediAsync(jedi);
        }
        
        public void deleteMatch(JediService.BusinessWCF.MatchWCF match) {
            base.Channel.deleteMatch(match);
        }
        
        public System.Threading.Tasks.Task deleteMatchAsync(JediService.BusinessWCF.MatchWCF match) {
            return base.Channel.deleteMatchAsync(match);
        }
        
        public void deleteStade(JediService.BusinessWCF.StadeWCF stade) {
            base.Channel.deleteStade(stade);
        }
        
        public System.Threading.Tasks.Task deleteStadeAsync(JediService.BusinessWCF.StadeWCF stade) {
            return base.Channel.deleteStadeAsync(stade);
        }
        
        public void deleteTournois(JediService.BusinessWCF.TournoiWCF tournoi) {
            base.Channel.deleteTournois(tournoi);
        }
        
        public System.Threading.Tasks.Task deleteTournoisAsync(JediService.BusinessWCF.TournoiWCF tournoi) {
            return base.Channel.deleteTournoisAsync(tournoi);
        }
        
        public void deleteCaracteristique(JediService.BusinessWCF.CaracteristiqueWCF caract) {
            base.Channel.deleteCaracteristique(caract);
        }
        
        public System.Threading.Tasks.Task deleteCaracteristiqueAsync(JediService.BusinessWCF.CaracteristiqueWCF caract) {
            return base.Channel.deleteCaracteristiqueAsync(caract);
        }
        
        public void updateJedi(JediService.BusinessWCF.JediWCF jedi) {
            base.Channel.updateJedi(jedi);
        }
        
        public System.Threading.Tasks.Task updateJediAsync(JediService.BusinessWCF.JediWCF jedi) {
            return base.Channel.updateJediAsync(jedi);
        }
        
        public void updateMatch(JediService.BusinessWCF.MatchWCF match) {
            base.Channel.updateMatch(match);
        }
        
        public System.Threading.Tasks.Task updateMatchAsync(JediService.BusinessWCF.MatchWCF match) {
            return base.Channel.updateMatchAsync(match);
        }
        
        public void updateStade(JediService.BusinessWCF.StadeWCF stade) {
            base.Channel.updateStade(stade);
        }
        
        public System.Threading.Tasks.Task updateStadeAsync(JediService.BusinessWCF.StadeWCF stade) {
            return base.Channel.updateStadeAsync(stade);
        }
        
        public void updateTournois(JediService.BusinessWCF.TournoiWCF tournoi) {
            base.Channel.updateTournois(tournoi);
        }
        
        public System.Threading.Tasks.Task updateTournoisAsync(JediService.BusinessWCF.TournoiWCF tournoi) {
            return base.Channel.updateTournoisAsync(tournoi);
        }
        
        public void updateCaracteristique(JediService.BusinessWCF.CaracteristiqueWCF caract) {
            base.Channel.updateCaracteristique(caract);
        }
        
        public System.Threading.Tasks.Task updateCaracteristiqueAsync(JediService.BusinessWCF.CaracteristiqueWCF caract) {
            return base.Channel.updateCaracteristiqueAsync(caract);
        }
        
        public JediService.BusinessWCF.TournoiWCF playTournoi(JediService.BusinessWCF.TournoiWCF tournoi) {
            return base.Channel.playTournoi(tournoi);
        }
        
        public System.Threading.Tasks.Task<JediService.BusinessWCF.TournoiWCF> playTournoiAsync(JediService.BusinessWCF.TournoiWCF tournoi) {
            return base.Channel.playTournoiAsync(tournoi);
        }
    }
}
