//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.34209
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestJediService.ServiceJediReference {
    using System.Runtime.Serialization;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EDefCaracteristique", Namespace="http://schemas.datacontract.org/2004/07/EntitiesLayer")]
    public enum EDefCaracteristique : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Force = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Defense = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Sante = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Chance = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ETypeCaracteristique", Namespace="http://schemas.datacontract.org/2004/07/EntitiesLayer")]
    public enum ETypeCaracteristique : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Jedi = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Stade = 1,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EPhaseTournoi", Namespace="http://schemas.datacontract.org/2004/07/EntitiesLayer")]
    public enum EPhaseTournoi : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        QuartFinale = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        HuitiemeFinale = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DemiFinale = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Finale = 3,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceJediReference.IServiceJedi")]
    public interface IServiceJedi {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceJedi/getAllJedi", ReplyAction="http://tempuri.org/IServiceJedi/getAllJediResponse")]
        System.Collections.Generic.List<JediService.BusinessWCF.JediWCF> getAllJedi();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceJedi/getAllJedi", ReplyAction="http://tempuri.org/IServiceJedi/getAllJediResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<JediService.BusinessWCF.JediWCF>> getAllJediAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceJedi/getAllMatch", ReplyAction="http://tempuri.org/IServiceJedi/getAllMatchResponse")]
        System.Collections.Generic.List<JediService.BusinessWCF.MatchWCF> getAllMatch();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceJedi/getAllMatch", ReplyAction="http://tempuri.org/IServiceJedi/getAllMatchResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<JediService.BusinessWCF.MatchWCF>> getAllMatchAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceJedi/getAllStade", ReplyAction="http://tempuri.org/IServiceJedi/getAllStadeResponse")]
        System.Collections.Generic.List<JediService.BusinessWCF.StadeWCF> getAllStade();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceJedi/getAllStade", ReplyAction="http://tempuri.org/IServiceJedi/getAllStadeResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<JediService.BusinessWCF.StadeWCF>> getAllStadeAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceJedi/getAllTournoi", ReplyAction="http://tempuri.org/IServiceJedi/getAllTournoiResponse")]
        System.Collections.Generic.List<JediService.BusinessWCF.TournoiWCF> getAllTournoi();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceJedi/getAllTournoi", ReplyAction="http://tempuri.org/IServiceJedi/getAllTournoiResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<JediService.BusinessWCF.TournoiWCF>> getAllTournoiAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceJedi/getAllCaracteristique", ReplyAction="http://tempuri.org/IServiceJedi/getAllCaracteristiqueResponse")]
        System.Collections.Generic.List<JediService.BusinessWCF.CaracteristiqueWCF> getAllCaracteristique();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceJedi/getAllCaracteristique", ReplyAction="http://tempuri.org/IServiceJedi/getAllCaracteristiqueResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<JediService.BusinessWCF.CaracteristiqueWCF>> getAllCaracteristiqueAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceJedi/addJedi", ReplyAction="http://tempuri.org/IServiceJedi/addJediResponse")]
        void addJedi(JediService.BusinessWCF.JediWCF j);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceJedi/addJedi", ReplyAction="http://tempuri.org/IServiceJedi/addJediResponse")]
        System.Threading.Tasks.Task addJediAsync(JediService.BusinessWCF.JediWCF j);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceJediChannel : TestJediService.ServiceJediReference.IServiceJedi, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceJediClient : System.ServiceModel.ClientBase<TestJediService.ServiceJediReference.IServiceJedi>, TestJediService.ServiceJediReference.IServiceJedi {
        
        public ServiceJediClient() {
        }
        
        public ServiceJediClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceJediClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceJediClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceJediClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<JediService.BusinessWCF.JediWCF> getAllJedi() {
            return base.Channel.getAllJedi();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<JediService.BusinessWCF.JediWCF>> getAllJediAsync() {
            return base.Channel.getAllJediAsync();
        }
        
        public System.Collections.Generic.List<JediService.BusinessWCF.MatchWCF> getAllMatch() {
            return base.Channel.getAllMatch();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<JediService.BusinessWCF.MatchWCF>> getAllMatchAsync() {
            return base.Channel.getAllMatchAsync();
        }
        
        public System.Collections.Generic.List<JediService.BusinessWCF.StadeWCF> getAllStade() {
            return base.Channel.getAllStade();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<JediService.BusinessWCF.StadeWCF>> getAllStadeAsync() {
            return base.Channel.getAllStadeAsync();
        }
        
        public System.Collections.Generic.List<JediService.BusinessWCF.TournoiWCF> getAllTournoi() {
            return base.Channel.getAllTournoi();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<JediService.BusinessWCF.TournoiWCF>> getAllTournoiAsync() {
            return base.Channel.getAllTournoiAsync();
        }
        
        public System.Collections.Generic.List<JediService.BusinessWCF.CaracteristiqueWCF> getAllCaracteristique() {
            return base.Channel.getAllCaracteristique();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<JediService.BusinessWCF.CaracteristiqueWCF>> getAllCaracteristiqueAsync() {
            return base.Channel.getAllCaracteristiqueAsync();
        }
        
        public void addJedi(JediService.BusinessWCF.JediWCF j) {
            base.Channel.addJedi(j);
        }
        
        public System.Threading.Tasks.Task addJediAsync(JediService.BusinessWCF.JediWCF j) {
            return base.Channel.addJediAsync(j);
        }
    }
}
